### ISSUE TITLE
msbuild task factory and vscode omnisharp

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#23]
Here is an interesting one for you.

For the hell of it I just opend my project in VSCode!
I have the latest VSCore (version 1.21.0)
I have the following extensions installed:

![image](https://user-images.githubusercontent.com/3176632/37257780-529f10de-2565-11e8-8bee-7bc41afb961e.png)

When I open the project I get this in the OUTPUT window - here is the full output:

> Starting OmniSharp server at 2018-3-11 19:46:52
    Target: e:\Repos\DotNet.Glob

> OmniSharp server started
    Path: C:\Users\Daz\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\OmniSharp.exe
    PID: 23732

> [info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.6.27428.2002 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Daz\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.6.27428.2002 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\Repos\DotNet.Glob'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Found 1 Cake files.
[warn]: OmniSharp.Cake.CakeProjectSystem
        Could not initialize Cake script service. Aborting.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in e:\Repos\DotNet.Glob
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'e:\Repos\DotNet.Glob'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Repos\DotNet.Glob\src\DotNet.Glob\DotNet.Glob.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Repos\DotNet.Glob\src\DotNet.Glob.Benchmarks\DotNet.Glob.Benchmarks.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Repos\DotNet.Glob\src\DotNet.Glob.Tests\DotNet.Glob.Tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\Repos\DotNet.Glob'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\Repos\DotNet.Glob\src\DotNet.Glob\DotNet.Glob.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\Repos\DotNet.Glob' on host 15780.
Exception when creating task: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at UtilPack.NuGet.AssemblyLoading.NuGetRestorerWrapper.ResolveNuGetPackageAssemblies(String[] packageID, String[] packageVersion, MarshaledResultSetter`1 setter)
   at UtilPack.NuGet.AssemblyLoading.NuGetAssemblyResolverImpl.UseResolver(String[] packageIDs, String[] packageVersions)
   at UtilPack.NuGet.AssemblyLoading.NuGetAssemblyResolverImpl.<LoadNuGetAssemblies>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E_UtilPack.<LoadNuGetAssembly>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.LoadTaskType(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, ConstructorInfo& taskConstructor, Object[]& constructorArguments, Boolean& usesDynamicLoading)
   at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
   at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.CreateExecutionHelper(String taskName, XElement taskBodyElement, String taskPackageID, String taskPackageVersion, String taskAssemblyFullPath, String taskAssemblyPathHint, BoundRestoreCommandUser restorer, ResolverLogger resolverLogger, GetFileItemsDelegate getFiles, String assemblyCopyTargetFolder, AppDomainSetup& appDomainSetup)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.<>c__DisplayClass30_3.<Initialize>b__3()

> WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

> [fail]: OmniSharp.MSBuild.ProjectLoader
        Exception in initialization: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at UtilPack.NuGet.AssemblyLoading.NuGetRestorerWrapper.ResolveNuGetPackageAssemblies(String[] packageID, String[] packageVersion, MarshaledResultSetter`1 setter)
   at UtilPack.NuGet.AssemblyLoading.NuGetAssemblyResolverImpl.UseResolver(String[] packageIDs, String[] packageVersions)
   at UtilPack.NuGet.AssemblyLoading.NuGetAssemblyResolverImpl.<LoadNuGetAssemblies>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E_UtilPack.<LoadNuGetAssembly>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.LoadTaskType(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, ConstructorInfo& taskConstructor, Object[]& constructorArguments, Boolean& usesDynamicLoading)
   at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
   at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.CreateExecutionHelper(String taskName, XElement taskBodyElement, String taskPackageID, String taskPackageVersion, String taskAssemblyFullPath, String taskAssemblyPathHint, BoundRestoreCommandUser restorer, ResolverLogger resolverLogger, GetFileItemsDelegate getFiles, String assemblyCopyTargetFolder, AppDomainSetup& appDomainSetup)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.<>c__DisplayClass30_3.<Initialize>b__3()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.Initialize(String taskName, IDictionary`2 parameterGroup, String taskBody, IBuildEngine taskFactoryLoggingHost)

> WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

> [fail]: OmniSharp.MSBuild.ProjectLoader
        The task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" could not be loaded from the assembly "C:\Users\Daz\.nuget\packages\utilpack.nuget.msbuild\2.4.0\build\net45\UtilPack.NuGet.MSBuild.dll". Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\Repos\DotNet.Glob\src\DotNet.Glob\DotNet.Glob.csproj'.
e:\Repos\DotNet.Glob\src\DotNet.Glob\DotNet.Glob.csproj

**Comment by stazz** [comment]
It seems that OmniSharp does not resolve assemblies located in the same directory as task factory assembly. That's because the `System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` assembly definetly is in the same folder (`C:\Users\Daz\.nuget\packages\utilpack.nuget.msbuild\2.4.0\build\net45`). But since it is not part of .NET framework (as such, ValueTuples are most likely in `mscorlib`, or maybe different version and/or public key), the lookup fails. IIRC MSBuild specifically tries to look in the task (factory) folder whenever assembly resolution fails, I guess OmniSharp hasn't picked that up.

All is not lost though - I think I could modify the .NET Desktop version of the task factory to hook up into assembly resolving event of current AppDomain in constructor, which would try to resolve assemblies located in the same folder. That should help in this scenario, I think.

**Comment by stazz** [comment]
The OmniSharp now successfuly loads UtilPack.NuGet.MSBuild task factory. The problem was that for some reason, even adding assembly binding redirects in `.dll.config` file, it would still both fail to locate the correct assembly (even though it was in same directory as task factory DLL), AND have already the `4.0.2.0` version loaded (because it is included in OmniSharp). Nevertheless, the issue has now been fixed, as .NET Desktop version of UtilPack.NuGet.MSBuild references the `4.0.2.0` version of System.ValueTuple now.

**Comment by dazinator** [comment]
Ah ok cool. I will give this another whirl some point soon :-) (once its released)

Weird the binding redirects were ignored, something must be setting up a custom appdomain or not using the config file you'd expect. I assume the config would sit with omnisharp if not vscode, and probably not the nicest solution to have to manually edit that anyway so probably turned out for the best :-)

**Comment by stazz** [comment]
Yeah, must've been poorly made AppDomainSetup (or maybe intentional?), or some other quirks of Desktop assembly loading logic. Anyway, closing this, and re-open if still fails once new version is release. :)
